default: &default
 host: localhost
 adapter: postgresql
 encoding: UTF8
 username: anasha
 timeout: 5000
 reaping_frequency: 30
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
 <<: *default
 database: expertise
 password: anasha

test:
 <<: *default
 database: expertise
 password: anasha

production:
 <<: *default
 database: expertise
 password: anasha


production:
  <<: *default
  database: expertise
  password: anasha
